<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'
import { useRouter } from 'vue-router'
import { useAuth } from '../stores/auth'
import { get, post } from '../api'
import { ElMessage } from 'element-plus'
import CloudTag from '../components/CloudTag.vue'
import StatusTag from '../components/StatusTag.vue'
import MetricChart from '../components/MetricChart.vue'
const router=useRouter(),auth=useAuth(),provider=ref(''),data=ref<any>({}),busy=ref(false)
async function load(){data.value=await get('/dashboard/summary',provider.value?{provider:provider.value}:{})}
watch(provider,load);onMounted(load)
async function sync(){busy.value=true;try{await post('/sync/all');ElMessage.success('同步任务已启动');router.push('/accounts')}finally{busy.value=false}}
const distribution=computed(()=>{const types=['vm','rds','lb','oss'];return ['aws','aliyun'].filter(p=>!provider.value||provider.value===p).map(p=>({name:p==='aws'?'AWS':'阿里云',points:types.map(t=>({value:data.value.distribution?.find((x:any)=>x.provider===p&&x.type===t)?.count||0}))}))})
const cpu=computed(()=>['aws','aliyun'].filter(p=>!provider.value||provider.value===p).map(p=>({name:p==='aws'?'AWS':'阿里云',points:(data.value.cpu_curve||[]).filter((x:any)=>x.provider===p).map((x:any)=>({time:x.hour,value:x.count?Math.round(x.sum/x.count*10)/10:0}))})))
const kpis=computed(()=>[{label:'纳管账号',value:data.value.accounts||0,note:'AWS / 阿里云',to:'/accounts'}, {label:'资源总数',value:data.value.resources||0,note:`4 类资源 · ${data.value.regions||0} 个地域`,to:'/resources'}, {label:'运行中主机',value:`${data.value.running_vms||0} / ${data.value.total_vms||0}`,note:`运行率 ${data.value.total_vms?((data.value.running_vms/data.value.total_vms)*100).toFixed(1):0}%`,to:'/resources?type=vm&status=running'}, {label:'闲置主机',value:data.value.idle_vms||0,note:'24 小时 CPU 均值低于 5%',to:'/resources?idle=1'}, {label:'30 天内到期',value:data.value.expiring||0,note:`最近一项 ${data.value.next_expiring_days||0} 天后到期`,to:'/resources?expiring=1'}])
</script>
<template><div class="page"><div class="page-head"><div><h1>概览</h1><p>{{data.accounts||0}} 个云账号 · {{data.regions||0}} 个地域 · 统一资源与监控视图</p></div><div class="toolbar" style="margin:0"><div class="cloud-segment"><button v-for="p in [{v:'',t:'全部'},{v:'aws',t:'AWS'},{v:'aliyun',t:'阿里云'}]" :key="p.v" :class="{active:provider===p.v}" @click="provider=p.v">{{p.t}}</button></div><el-button v-if="auth.admin" type="primary" :loading="busy" @click="sync">立即同步</el-button></div></div>
<div v-if="!data.accounts" class="card onboarding"><div class="onboard-icon">☁</div><h2>接入第一个云账号</h2><p>平台只需要只读权限。填写 AccessKey 后会自动校验凭证、发现可用地域并同步资源。</p><el-button v-if="auth.admin" type="primary" @click="router.push('/accounts?new=1')">新增云账号</el-button><p v-else>请联系管理员添加云账号</p><div class="steps"><div><b>01</b><strong>创建只读 AccessKey</strong><p>为 AWS IAM 或阿里云 RAM 用户授予只读策略</p></div><div><b>02</b><strong>测试连接并选择地域</strong><p>通过 STS 验证身份，选择需要同步的地域</p></div><div><b>03</b><strong>自动同步资源</strong><p>保存后同步，此后可手动刷新</p></div></div><div class="grid-2 perms"><div><h3>AWS 所需权限</h3><p>ReadOnlyAccess 或 STS、EC2、RDS、ELB、S3、CloudWatch 的只读动作</p></div><div><h3>阿里云所需权限</h3><p>ECS、RDS、SLB、ALB、OSS、CloudMonitor 的 ReadOnlyAccess 策略</p></div></div></div>
<template v-else><div class="kpis"><router-link v-for="(k,i) in kpis" :key="k.label" :to="k.to" class="card kpi" :class="{warn:i===4}"><div class="kpi-label">{{k.label}}<span>{{['◇','▤','⌁','◉','◷'][i]}}</span></div><strong>{{k.value}}</strong><small>{{k.note}}</small></router-link></div>
<div class="grid-2 charts"><section class="card panel"><div class="section-head"><h2 class="section-title">资源分布</h2><span class="legend"><i></i>AWS　<i class="ali"></i>阿里云</span></div><MetricChart kind="bar" :series="distribution" :categories="['云主机','数据库','负载均衡','对象存储']" :height="240"/></section><section class="card panel"><div class="section-head"><h2 class="section-title">主机 CPU 均值 · 近 24 小时</h2><span class="legend"><i></i>AWS　<i class="ali"></i>阿里云</span></div><MetricChart :series="cpu" unit="%" :height="240"/></section></div>
<div class="grid-3 lower"><section class="card panel"><div class="section-head"><h2 class="section-title">CPU 使用率 Top 5</h2><router-link class="subtle-link" to="/resources?type=vm&sort=cpu_1h">查看全部</router-link></div><div v-for="(r,i) in data.top_cpu||[]" :key="r.id" class="rank"><span class="rank-no">{{Number(i)+1}}</span><div class="rank-main"><router-link :to="`/resources?detail=${r.id}`">{{r.name}}</router-link><small><CloudTag :provider="r.provider"/> {{r.region}}</small></div><div class="rank-value">{{r.cpu_1h?.toFixed(1)}}%</div></div></section><section class="card panel"><div class="section-head"><h2 class="section-title">即将到期</h2><router-link class="subtle-link" to="/resources?expiring=1">全部 {{data.expiring}} 项</router-link></div><div v-for="r in data.expiring_items||[]" :key="r.id" class="expiry"><div><router-link :to="`/resources?detail=${r.id}`">{{r.name}}</router-link><small>{{r.type}} · {{r.region}}</small></div><b>{{Math.max(0,Math.ceil((new Date(r.expires_at).getTime()-Date.now())/86400000))}} 天</b></div></section><section class="card panel"><div class="section-head"><h2 class="section-title">最近同步</h2><router-link class="subtle-link" to="/accounts">同步历史</router-link></div><div v-for="j in data.recent_sync||[]" :key="j.id" class="sync-row"><CloudTag :provider="j.provider"/><span>{{j.account_name}}</span><StatusTag :status="j.status"/></div></section></div></template></div></template>
<style scoped>.kpis{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin-bottom:12px}.kpi{padding:18px 18px;transition:transform .15s,box-shadow .15s}.kpi:hover{transform:translateY(-2px);box-shadow:0 8px 20px #19284b12}.kpi.warn{background:#FFFBF3;border-color:#F2E6CE}.kpi-label{font-size:12px;color:var(--muted);display:flex;justify-content:space-between}.kpi-label span{font-size:17px;color:#A0A8B8}.kpi strong{display:block;font-size:26px;font-weight:600;margin:12px 0 6px}.kpi small{color:var(--subtle);font-size:11px}.charts{margin-bottom:12px}.lower{grid-template-columns:1.1fr 1fr 1fr}.legend{color:var(--subtle);font-size:11px}.legend i{display:inline-block;width:7px;height:7px;background:var(--aws);border-radius:50%;margin-right:4px}.legend i.ali{background:var(--ali)}.rank,.expiry,.sync-row{display:flex;align-items:center;gap:10px;border-bottom:1px solid var(--divider);min-height:48px;font-size:12px}.rank:last-child,.expiry:last-child,.sync-row:last-child{border:0}.rank-no{background:#F1F3F7;color:#687386;width:20px;height:20px;border-radius:4px;display:grid;place-items:center;font:11px 'IBM Plex Mono'}.rank-main{flex:1;min-width:0}.rank-main a,.expiry a{font-weight:600}.rank-main small,.expiry small{display:block;color:var(--subtle);font-size:10px;margin-top:3px}.rank-main :deep(.tag-cloud){font-size:9px;padding:1px 4px}.rank-value{font-family:'IBM Plex Mono';color:var(--red);font-size:12px}.expiry{justify-content:space-between}.expiry b{font-size:11px;color:var(--amber);background:#FEF6E7;padding:4px 6px;border-radius:4px}.sync-row span:nth-child(2){flex:1}.onboarding{text-align:center;padding:52px 48px}.onboard-icon{font-size:52px;color:var(--primary)}.onboarding h2{font-size:24px}.onboarding>p{color:var(--subtle)}.steps{text-align:left;display:grid;grid-template-columns:repeat(3,1fr);gap:20px;margin:48px 0}.steps>div{border-top:2px solid var(--primary);padding-top:18px}.steps b{display:block;color:var(--primary);font-family:'IBM Plex Mono';margin-bottom:12px}.steps strong{display:block}.steps p,.perms p{color:var(--subtle);font-size:12px;line-height:1.7}.perms{text-align:left}.perms>div{background:#F8F9FC;padding:15px;border-radius:8px}.perms h3{font-size:14px}@media(max-width:1200px){.kpis{grid-template-columns:repeat(3,1fr)}}@media(max-width:700px){.kpis{grid-template-columns:repeat(2,1fr)}.steps{grid-template-columns:1fr}}</style>
