<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuth } from '../stores/auth'
const router=useRouter(),auth=useAuth(),username=ref('admin'),password=ref(''),busy=ref(false)
async function submit(){busy.value=true;try{await auth.login(username.value,password.value);router.replace('/dashboard')}finally{busy.value=false}}
</script>
<template><div class="login"><section class="hero"><div class="hero-brand"><span class="hero-logo">云</span><span>云枢 <small>多云运维聚合平台</small></span></div><div class="hero-copy"><div class="eyebrow">CLOUD OPERATIONS, UNIFIED</div><h1>跨云资源，<br>一处掌握。</h1><p>将 AWS 与阿里云的账号、资源和监控数据汇聚在同一个只读工作台。</p><div class="hero-points"><div>01 <span>多账号资源统一检索</span></div><div>02 <span>跨云监控趋势对比</span></div><div>03 <span>只读接入，操作可追溯</span></div></div></div><footer>© 2026 云枢 · v0.1</footer></section><section class="form-side"><div class="form-box"><h2>欢迎回来</h2><p>登录云枢，查看您的多云资源</p><el-form label-position="top" @submit.prevent="submit"><el-form-item label="用户名"><el-input v-model="username" size="large" placeholder="请输入用户名"/></el-form-item><el-form-item label="密码"><el-input v-model="password" size="large" type="password" show-password placeholder="请输入密码" @keydown.enter="submit"/></el-form-item><el-button type="primary" size="large" :loading="busy" class="login-button" @click="submit">登录平台</el-button></el-form><div class="login-note">首次启动时，管理员初始密码显示在服务端日志中。连续输错 5 次将暂时锁定账号。</div></div></section></div></template>
<style scoped>.login{min-height:100vh;display:grid;grid-template-columns:48% 52%;background:#fff}.hero{background:linear-gradient(145deg,#17338e,#102464);color:white;padding:46px 60px;display:flex;flex-direction:column;position:relative;overflow:hidden}.hero:after{content:'';position:absolute;width:650px;height:650px;border:1px solid #ffffff19;border-radius:50%;right:-280px;bottom:-250px;box-shadow:0 0 0 90px #ffffff08,0 0 0 180px #ffffff06}.hero-brand{display:flex;align-items:center;gap:12px;font-size:23px;font-weight:600;position:relative;z-index:1}.hero-brand small{display:block;font-size:11px;font-weight:400;opacity:.65}.hero-logo{display:grid;place-items:center;width:42px;height:42px;border:1px solid #ffffff66;border-radius:11px}.hero-copy{margin:auto 0;max-width:510px;position:relative;z-index:1}.eyebrow{font:12px 'IBM Plex Mono',monospace;letter-spacing:2px;color:#A7BCFF}.hero h1{font-size:48px;line-height:1.25;margin:24px 0;font-weight:600}.hero p{font-size:15px;line-height:1.9;color:#CAD5FF}.hero-points{margin-top:50px;border-top:1px solid #ffffff33}.hero-points div{padding:15px 0;border-bottom:1px solid #ffffff33;color:#A7BCFF;font:13px 'IBM Plex Mono',monospace}.hero-points span{font-family:inherit;color:white;margin-left:23px}.hero footer{font-size:12px;color:#B2C2ED;position:relative;z-index:1}.form-side{display:grid;place-items:center;padding:40px}.form-box{width:min(100%,390px)}.form-box h2{font-size:27px;margin:0 0 10px}.form-box>p{color:var(--subtle);margin:0 0 42px}.form-box :deep(.el-form-item){margin-bottom:24px}.login-button{width:100%;margin-top:10px}.login-note{margin-top:32px;padding:14px 16px;background:#F7F8FB;color:var(--subtle);font-size:12px;line-height:1.7;border-radius:8px}@media(max-width:800px){.login{grid-template-columns:1fr}.hero{display:none}}</style>
