<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { get, post } from '../api'
import CloudTag from '../components/CloudTag.vue'
import MetricChart from '../components/MetricChart.vue'
const route=useRoute(),router=useRouter(),type=ref(String(route.query.type||'vm')),metric=ref(String(route.query.metric||'cpu')),range=ref(String(route.query.range||'24h')),ids=ref<number[]>(String(route.query.ids||'').split(',').filter(Boolean).map(Number)),catalog=ref<any[]>([]),search=ref(''),options=ref<any[]>([]),series=ref<any[]>([]),loading=ref(false)
const metrics=computed(()=>catalog.value.filter(x=>x.types?.includes(type.value)))
async function find(){options.value=(await get('/resources',{type:type.value,q:search.value,page_size:20})).items||[]}
function add(id:number){if(ids.value.includes(id)||ids.value.length>=4)return;ids.value.push(id);search.value=''}
function remove(id:number){ids.value=ids.value.filter(x=>x!==id)}
async function query(){router.replace({query:{type:type.value,metric:metric.value,range:range.value,ids:ids.value.join(',')}});if(!ids.value.length){series.value=[];return};loading.value=true;try{series.value=(await post('/metrics/query',{ids:ids.value,metric:metric.value,range:range.value})).items||[]}finally{loading.value=false}}
watch([type,metric,range,ids],query,{deep:true});watch(search,find)
onMounted(async()=>{catalog.value=(await get('/metrics/catalog')).items||[];await find();await query()})
function changeType(){ids.value=[];metric.value='cpu'}
</script><template><div class="page"><div class="page-head"><div><h1>监控中心</h1><p>实时查询云监控指标，最多叠加 4 个资源进行跨云对比</p></div></div><div class="card panel"><div class="toolbar"><div class="cloud-segment"><button v-for="t in [{v:'vm',n:'云主机'},{v:'rds',n:'数据库'},{v:'lb',n:'负载均衡'},{v:'oss',n:'对象存储'}]" :key="t.v" :class="{active:type===t.v}" @click="type=t.v;changeType()">{{t.n}}</button></div><div style="flex:1"></div><el-segmented v-model="range" :options="['1h','6h','24h','7d']"/></div><div class="metric-pills"><button v-for="m in metrics" :key="m.key" :class="{active:metric===m.key}" @click="metric=m.key">{{m.name}} <small v-if="m.providers?.length===1">仅{{m.providers[0]==='aws'?'AWS':'阿里云'}}</small></button></div><div class="resource-select"><div><h3 class="section-title">对比资源 <small>（{{ids.length}} / 4）</small></h3><p class="muted">搜索名称、ID 或 IP，添加到图表中</p></div><el-select v-model="search" filterable remote clearable placeholder="搜索并添加资源" style="width:320px" :remote-method="(q:string)=>search=q" @change="(v:any)=>{if(v)add(Number(v))}"><el-option v-for="r in options.filter((x:any)=>!ids.includes(x.id))" :key="r.id" :value="r.id" :label="`${r.name} · ${r.region}`"/></el-select></div><div v-if="ids.length" class="selected"><span v-for="(id,i) in ids" :key="id" class="selected-chip"><i :style="{background:['#2443B5','#E07A1F','#13866F','#8B3FB8'][i]}"></i>{{series.find((s:any)=>s.resource_id===id)?.name||options.find((x:any)=>x.id===id)?.name||id}} <button @click="remove(id)">×</button></span></div><div class="chart-wrap"><div class="section-head"><h2 class="section-title">{{metrics.find((m:any)=>m.key===metric)?.name||'指标'}}趋势</h2><span class="muted">{{range}} · {{metrics.find((m:any)=>m.key===metric)?.unit}}</span></div><MetricChart v-if="series.some((x:any)=>x.supported)" :series="series.filter((x:any)=>x.supported)" :height="330" :unit="metrics.find((m:any)=>m.key===metric)?.unit"/><div v-else class="empty">{{ids.length?'所选资源不提供此指标':'选择资源后显示监控曲线'}}</div></div><div v-if="series.length" class="stat-grid"><div v-for="(s,i) in series" :key="s.resource_id" class="stat"><div class="stat-name"><i :style="{background:['#2443B5','#E07A1F','#13866F','#8B3FB8'][i]}"></i><strong>{{s.name}}</strong><CloudTag :provider="s.provider"/></div><template v-if="s.supported"><span>当前 <b>{{s.current}} {{s.unit}}</b></span><span>平均 <b>{{s.average}} {{s.unit}}</b></span><span>最大 <b>{{s.max}} {{s.unit}}</b></span></template><span v-else class="muted">该资源不提供此指标</span></div></div></div></div></template>
<style scoped>.metric-pills{display:flex;gap:8px;flex-wrap:wrap;padding-bottom:24px;border-bottom:1px solid var(--divider)}.metric-pills button{border:1px solid var(--border);background:white;border-radius:18px;padding:8px 14px;color:var(--muted);cursor:pointer}.metric-pills button.active{border-color:var(--primary);color:var(--primary);background:var(--primary-soft);font-weight:600}.metric-pills small{font-size:10px;margin-left:5px;color:var(--subtle)}.resource-select{display:flex;justify-content:space-between;align-items:center;margin:24px 0 12px}.resource-select small{font-size:12px;color:var(--subtle)}.resource-select p{font-size:12px;margin:5px 0}.selected{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:20px}.selected-chip{display:flex;gap:7px;align-items:center;border:1px solid var(--border);border-radius:6px;padding:7px 9px;font-size:12px}.selected-chip i,.stat-name i{width:7px;height:7px;border-radius:50%}.selected-chip button{background:none;border:0;color:var(--subtle);cursor:pointer}.chart-wrap{padding:20px;border:1px solid var(--divider);border-radius:8px}.stat-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin-top:14px}.stat{border:1px solid var(--divider);border-radius:8px;padding:14px;display:flex;gap:18px;align-items:center;font-size:12px}.stat-name{display:flex;align-items:center;gap:7px;flex:1}.stat b{font-family:'IBM Plex Mono'}</style>
