<script setup lang="ts">
import { ref, watch, onMounted, computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { get } from '../api'
import CloudTag from '../components/CloudTag.vue'
import StatusTag from '../components/StatusTag.vue'
import MetricChart from '../components/MetricChart.vue'
const route=useRoute(),router=useRouter(),types=[{v:'vm',t:'云主机'},{v:'rds',t:'数据库'},{v:'lb',t:'负载均衡'},{v:'oss',t:'对象存储'}],type=ref(String(route.query.type||'vm')),provider=ref(String(route.query.provider||'')),q=ref(String(route.query.q||'')),region=ref(''),status=ref(''),account=ref(''),page=ref(1),items=ref<any[]>([]),total=ref(0),filters=ref<any>({}),accounts=ref<any[]>([]),detail=ref<any>(null),drawer=ref(false),detailTab=ref('basic'),metricRange=ref('24h'),metrics=ref<any[]>([]),sort=ref(String(route.query.sort||'')),idle=ref(route.query.idle==='1'),expiring=ref(route.query.expiring==='1')
async function load(){const params:any={type:type.value,provider:provider.value,q:q.value,region:region.value,status:status.value,account_id:account.value,page:page.value,page_size:20,sort:sort.value,idle:idle.value?'1':'',expiring:expiring.value?'1':''};const r=await get('/resources',params);items.value=r.items||[];total.value=r.total||0;filters.value=await get('/resources/filters',{provider:provider.value,q:q.value});}
async function open(id:number){detail.value=await get(`/resources/${id}`);drawer.value=true;detailTab.value='basic';metricRange.value='24h';await loadMetrics();router.replace({query:{...route.query,detail:String(id)}})}
async function loadMetrics(){if(detail.value)metrics.value=(await get(`/resources/${detail.value.id}/metrics`,{range:metricRange.value})).items||[]}
function close(){drawer.value=false;const query={...route.query};delete query.detail;router.replace({query})}
function compare(){router.push({path:'/monitor',query:{type:detail.value.type,metric:'cpu',ids:String(detail.value.id),range:'24h'}})}
function copy(v:string){navigator.clipboard.writeText(v)}
function extraOf(resource:any){try{return JSON.parse(resource?.extra||'{}')}catch{return {}}}
function displayExtra(value:any){if(value===null||value===undefined||value==='')return '—';if(Array.isArray(value))return value.join(', ')||'—';if(typeof value==='object')return JSON.stringify(value);if(typeof value==='number')return value.toLocaleString('zh-CN',{maximumFractionDigits:2});return String(value)}
watch([type,provider,q,region,status,account,sort,idle,expiring],()=>{page.value=1;load()});watch(page,load);watch(metricRange,loadMetrics)
onMounted(async()=>{accounts.value=(await get('/accounts')).items||[];await load();if(route.query.detail)open(Number(route.query.detail))})
const typeLabel=computed(()=>types.find(x=>x.v===type.value)?.t)
const detailExtra=computed(()=>extraOf(detail.value))
const extraLabels:any={os:'操作系统',subnet:'子网 / 交换机',subnet_group:'子网组',security_groups:'安全组',network_performance:'网络性能',internet_bandwidth_in_mbps:'公网入带宽上限（Mbps）',internet_bandwidth_out_mbps:'公网出带宽上限（Mbps）',engine:'数据库引擎',engine_version:'引擎版本',storage_gb:'存储容量（GB）',storage_type:'存储类型',endpoint:'访问地址',port:'端口',vpc:'VPC',availability_zone:'可用区',availability_zones:'可用区',multi_az:'多可用区',publicly_accessible:'公网可访问',max_connections:'最大连接数',dns:'DNS',scheme:'网络类型',bandwidth:'带宽',edition:'版本',ip_address_type:'地址类型',location:'存储地域',storage_class:'存储类型',capacity_gb:'存储容量（GB）',object_count:'对象数量',multipart_upload_count:'未完成分片上传',stats_updated_at:'容量统计时间',created_at:'云端创建时间'}
const metricNames:any={cpu:'CPU 使用率',memory:'内存使用率',network_in:'网络流入',network_out:'网络流出',connections:'连接数',qps:'请求数',storage:'存储空间'}
</script>
<template><div class="page"><div class="page-head"><div><h1>资源中心</h1><p>跨云、跨账号、跨地域统一检索资源</p></div></div><div class="card content"><div class="tabs"><button v-for="t in types" :key="t.v" :class="{active:type===t.v}" @click="type=t.v">{{t.t}} <span>{{filters.types?.find((x:any)=>x.type===t.v)?.count||0}}</span></button></div><div class="toolbar"><div class="cloud-segment"><button v-for="p in [{v:'',t:'全部'},{v:'aws',t:'AWS'},{v:'aliyun',t:'阿里云'}]" :key="p.v" :class="{active:provider===p.v}" @click="provider=p.v">{{p.t}}</button></div><el-select v-model="account" clearable placeholder="全部账号" style="width:145px"><el-option v-for="a in accounts" :key="a.id" :label="a.name" :value="a.id"/></el-select><el-select v-model="region" clearable placeholder="全部地域" style="width:155px"><el-option v-for="r in filters.regions||[]" :key="r" :label="r" :value="r"/></el-select><el-select v-model="status" clearable placeholder="全部状态" style="width:130px"><el-option v-for="s in filters.statuses||[]" :key="s" :label="s" :value="s"/></el-select><el-input v-model="q" clearable placeholder="名称 / ID / IP / env:prod" style="width:260px"/><el-button v-if="idle" type="primary" plain @click="idle=false">闲置 ×</el-button><el-button v-if="expiring" type="warning" plain @click="expiring=false">即将到期 ×</el-button></div>
<el-table :data="items" row-key="id" @row-click="(r:any)=>open(r.id)"><el-table-column label="名称 / ID" min-width="220"><template #default="{row}"><div class="name">{{row.name}}</div><div class="mono muted id-text">{{row.cloud_id}}</div></template></el-table-column><el-table-column label="云厂商" width="95"><template #default="{row}"><CloudTag :provider="row.provider"/></template></el-table-column><el-table-column label="地域" prop="region" width="145"/><el-table-column label="规格" prop="spec" min-width="120"/><el-table-column v-if="type==='vm'" label="内网 IP" width="125"><template #default="{row}"><span class="mono">{{row.ip||'—'}}</span></template></el-table-column><el-table-column v-if="type==='vm'" label="vCPU / 内存" width="120"><template #default="{row}">{{row.vcpu}} 核 / {{row.memory_gb}} GB</template></el-table-column><el-table-column v-if="type==='rds'" label="引擎 / 存储" min-width="155"><template #default="{row}">{{extraOf(row).engine||'—'}} {{extraOf(row).engine_version||''}}<div class="muted sm">{{displayExtra(extraOf(row).storage_gb)}} GB · {{extraOf(row).storage_type||'—'}}</div></template></el-table-column><el-table-column v-if="type==='rds'" label="访问地址" min-width="180"><template #default="{row}"><span class="mono sm">{{extraOf(row).endpoint||row.ip||'—'}}</span></template></el-table-column><el-table-column v-if="type==='lb'" label="地址 / DNS" min-width="190"><template #default="{row}"><span class="mono sm">{{row.ip||extraOf(row).dns||'—'}}</span></template></el-table-column><el-table-column v-if="type==='oss'" label="容量" width="120"><template #default="{row}"><span class="mono">{{extraOf(row).capacity_gb===undefined?'—':displayExtra(extraOf(row).capacity_gb)+' GB'}}</span></template></el-table-column><el-table-column v-if="type==='oss'" label="对象数" width="110"><template #default="{row}"><span class="mono">{{displayExtra(extraOf(row).object_count)}}</span></template></el-table-column><el-table-column label="状态" width="110"><template #default="{row}"><StatusTag :status="row.status"/></template></el-table-column><el-table-column v-if="type==='vm'" label="CPU 近 1h" width="120"><template #default="{row}"><span v-if="row.metrics_at" class="mono">{{row.cpu_1h?.toFixed(1)}}%</span><span v-else class="muted">—</span><el-tag v-if="row.metrics_at&&row.status==='running'&&row.cpu_24h<(filters.idle_cpu_threshold||5)" size="small" type="info" style="margin-left:4px">闲置</el-tag></template></el-table-column><el-table-column label="到期" width="120"><template #default="{row}"><span v-if="row.expires_at" :class="{expiring:new Date(row.expires_at).getTime()-Date.now()<(filters.expiring_days||30)*86400000}">{{new Date(row.expires_at).toLocaleDateString('zh-CN')}}</span><span v-else class="muted">—</span></template></el-table-column></el-table><div v-if="!items.length" class="empty">暂无{{typeLabel}}资源</div><div class="pager"><span>共 {{total}} 项</span><el-pagination v-model:current-page="page" :total="total" :page-size="20" layout="prev,pager,next"/></div></div>
<el-drawer v-model="drawer" size="min(760px,90vw)" :with-header="false" @close="close"><div v-if="detail" class="drawer"><div class="drawer-head"><div><div class="muted" style="font-size:12px">资源详情 / {{typeLabel}}</div><h2>{{detail.name}}</h2><div class="drawer-tags"><CloudTag :provider="detail.provider"/><StatusTag :status="detail.status"/><span class="muted">{{detail.region}}</span></div></div><el-button text @click="drawer=false">✕</el-button></div><el-tabs v-model="detailTab"><el-tab-pane label="基本信息" name="basic"><div class="detail-grid"><div v-for="[label,value] in [['资源 ID',detail.cloud_id],['账号 ID',detail.account_id],['地域',detail.region],['规格',detail.spec],['内网 IP / 地址',detail.ip||'—'],['vCPU',detail.vcpu||'—'],['内存',detail.memory_gb?detail.memory_gb+' GB':'—'],['首次发现',new Date(detail.created_at).toLocaleString('zh-CN')],['到期时间',detail.expires_at?new Date(detail.expires_at).toLocaleString('zh-CN'):'—']]" :key="label"><small>{{label}}</small><span>{{value}}</span></div></div><h3 v-if="Object.keys(detailExtra).length" class="section-title extra-title">云端属性</h3><div v-if="Object.keys(detailExtra).length" class="detail-grid"><div v-for="(value,key) in detailExtra" :key="key"><small>{{extraLabels[key]||key}}</small><span :class="{errorValue:String(key).endsWith('_error')}">{{displayExtra(value)}}</span></div></div><el-button style="margin-top:20px" @click="copy(detail.cloud_id)">复制资源 ID</el-button></el-tab-pane><el-tab-pane label="标签" name="tags"><div v-for="(v,k) in JSON.parse(detail.tags||'{}')" :key="k" class="tag-line"><b>{{k}}</b><span>{{v}}</span></div><div v-if="!Object.keys(JSON.parse(detail.tags||'{}')).length" class="empty">该资源没有标签，或当前凭证缺少读取标签权限</div></el-tab-pane><el-tab-pane label="监控" name="metrics"><div class="toolbar"><el-segmented v-model="metricRange" :options="['1h','6h','24h','7d']"/><el-button type="primary" plain @click="compare">在监控中心对比</el-button></div><div class="metric-grid"><div v-for="m in metrics" :key="m.metric" class="card panel"><div class="section-head"><h3 class="section-title">{{metricNames[m.metric]||m.metric}}</h3><span class="mono muted">当前 {{m.current}} {{m.unit}}</span></div><MetricChart v-if="m.supported&&!m.error" :series="[m]" :height="155" :unit="m.unit"/><div v-else class="empty">{{m.error||'该资源不提供此指标'}}</div><small v-if="m.supported&&!m.error" class="muted">平均 {{m.average}} {{m.unit}}　 最大 {{m.max}} {{m.unit}}</small></div></div></el-tab-pane><el-tab-pane label="原始数据" name="raw"><el-button @click="copy(JSON.stringify(detail,null,2))">复制 JSON</el-button><pre>{{JSON.stringify(detail,null,2)}}</pre></el-tab-pane></el-tabs></div></el-drawer></div></template>
<style scoped>.content{padding:0 20px 18px}.tabs{display:flex;border-bottom:1px solid var(--divider);margin-bottom:16px;gap:28px}.tabs button{border:0;background:none;padding:17px 3px;color:var(--muted);cursor:pointer;border-bottom:2px solid transparent}.tabs button.active{color:var(--primary);border-color:var(--primary);font-weight:600}.tabs span{font-family:'IBM Plex Mono';font-size:11px;background:#F2F4F7;border-radius:4px;padding:2px 5px;margin-left:3px}.name{font-weight:600;color:var(--primary);cursor:pointer}.id-text{font-size:11px;margin-top:5px}.sm{font-size:11px}.pager{display:flex;justify-content:space-between;align-items:center;padding-top:16px;color:var(--subtle);font-size:12px}.expiring{color:var(--amber);font-weight:600}.drawer{padding:22px}.drawer-head{display:flex;justify-content:space-between;align-items:start;border-bottom:1px solid var(--divider);padding-bottom:16px}.drawer-head h2{margin:8px 0;font-size:20px}.drawer-tags{display:flex;gap:12px;align-items:center}.detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-top:18px}.detail-grid small{display:block;color:var(--subtle);margin-bottom:5px}.detail-grid span{font-size:13px;font-family:'IBM Plex Mono',sans-serif;overflow-wrap:anywhere}.extra-title{margin-top:28px}.errorValue{color:var(--red)}.tag-line{display:flex;gap:20px;padding:12px;border-bottom:1px solid var(--divider)}.tag-line b{min-width:120px}.metric-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.drawer pre{background:#F7F8FB;padding:15px;overflow:auto;font:12px 'IBM Plex Mono'}</style>
